---
apiVersion: v1
kind: Service
metadata:
  name: clients
  labels:
    app.kubernetes.io/component: zeebe-client
    {{- include "camunda-load-tests.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}{{ include "camunda-load-tests.commonLabels" . | nindent 4 }}{{- end }}
spec:
  selector:
    app.kubernetes.io/component: zeebe-client
  ports:
  - name: http
    port: 9600
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clients
  labels:
    release: monitoring
    {{- include "camunda-load-tests.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}{{ include "camunda-load-tests.commonLabels" . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: zeebe-client
  endpoints:
  - honorLabels: true
    # since - is not supported directly, we have to use the index function and quote "camunda-platform"
    interval: 30s
    path: /metrics
    port: http
