{{- if .Values.global.extraConfig }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: load-test-config
  labels: {{- include "camunda-load-tests.labels" . | nindent 4 }}
data:
  load-test-config.yaml: |
    # Extra configuration for the load test applications
    {{- .Values.global.extraConfig | toYaml | nindent 4 -}}
{{- end }}