apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter
  labels:
    app: starter
    {{- include "camunda-load-tests.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: starter
  replicas: {{ .Values.starter.replicas }}
  template:
    metadata:
      labels:
        app: starter
        app.kubernetes.io/component: zeebe-client
        {{- include "camunda-load-tests.labels" . | nindent 8 }}
      annotations:
        {{- include "camunda-load-tests.annotations" $ | nindent 8 }}
    spec:
      {{- if .Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.image.pullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: starter
          image: "{{ .Values.global.image.repository }}/starter:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                {{- if $.Values.saas.enabled }}
                -Dapp.tls=true
                {{- else }}
                -Dapp.brokerUrl=http://{{ $.Values.global.connect.serviceName }}:26500
                -Dapp.brokerRestUrl=http://{{ $.Values.global.connect.serviceName }}:8080
                {{- end }}
                -Dapp.preferRest={{ .Values.global.preferRest.enabled }}
                -Dapp.performReadBenchmarks={{ .Values.global.performReadBenchmarks }}
                -Dapp.starter.rate={{ .Values.starter.rate }}
                {{- if .Values.starter.rateDuration }}
                -Dapp.starter.rateDuration={{ .Values.starter.rateDuration }}
                {{- end }}
                {{- if .Values.starter.durationLimit }}
                -Dapp.starter.durationLimit={{ .Values.starter.durationLimit }}
                {{- end }}
                -Dzeebe.client.requestTimeout=62000
                {{- if .Values.starter.processId }}
                -Dapp.starter.processId={{ .Values.starter.processId | quote }}
                {{- end }}
                {{- if .Values.starter.bpmnXmlPath }}
                -Dapp.starter.bpmnXmlPath={{ .Values.starter.bpmnXmlPath | quote }}
                {{- end }}
                {{- range $index, $value := .Values.starter.extraResources }}
                -Dapp.starter.extraBpmnModels.{{ $index }}={{ $value | quote }}
                {{- end }}
                {{- if .Values.starter.businessKey }}
                -Dapp.starter.businessKey={{ .Values.starter.businessKey | quote }}
                {{- end }}
                {{- if .Values.starter.payloadPath }}
                -Dapp.starter.payloadPath={{ .Values.starter.payloadPath | quote }}
                {{- end }}
                -XX:+HeapDumpOnOutOfMemoryError
            {{- if .Values.starter.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.starter.logLevel | quote }}
            {{- end }}
            {{- if $.Values.saas.enabled }}
            - name: ZEEBE_REST_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: zeebeRestAddress
            - name: ZEEBE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: clientId
            - name: ZEEBE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: clientSecret
            - name: ZEEBE_AUTHORIZATION_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: authServer
            - name: ZEEBE_TOKEN_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: authorizationAudience
            - name: ZEEBE_AUTH_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: authType
            - name: ZEEBE_GRPC_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: zeebeGrpcAddress
            {{- end }}
            {{- if .Values.global.extraConfig }}
            # To be able to load a separate/additional configuration
            - name: SPRING_CONFIG_ADDITIONALLOCATION
              value: "/usr/local/camunda/config/load-test-config.yaml"
            {{- end }}
            {{- range $keyValue := $.Values.global.extraEnvVars }}
            - name: {{ $keyValue.name }}
              {{- if $keyValue.valueFrom }}
              valueFrom:
                {{- toYaml $keyValue.valueFrom | nindent 16 }}
              {{- else }}
              value: {{ $keyValue.value | quote }}
              {{- end }}
            {{- end }}
            ##
            ## Spring Boot compatible env vars (for migrated load tester, ignored by old HOCON app)
            ##
            - name: CAMUNDA_CLIENT_PREFER_REST_OVER_GRPC
              value: {{ .Values.global.preferRest.enabled | quote }}
            - name: LOAD_TESTER_PERFORM_READ_BENCHMARKS
              value: {{ .Values.global.performReadBenchmarks | quote }}
            {{- if not $.Values.saas.enabled }}
            - name: CAMUNDA_CLIENT_GRPC_ADDRESS
              value: "http://{{ $.Values.global.connect.serviceName }}:26500"
            - name: CAMUNDA_CLIENT_REST_ADDRESS
              value: "http://{{ $.Values.global.connect.serviceName }}:8080"
            {{- else }}
            - name: CAMUNDA_CLIENT_MODE
              value: "saas"
            - name: CAMUNDA_CLIENT_AUTH_METHOD
              value: "oidc"
            {{- end }}
            - name: LOAD_TESTER_STARTER_RATE
              value: {{ .Values.starter.rate | quote }}
            {{- if .Values.starter.rateDuration }}
            - name: LOAD_TESTER_STARTER_RATE_DURATION
              value: {{ .Values.starter.rateDuration | quote }}
            {{- end }}
            {{- if .Values.starter.durationLimit }}
            - name: LOAD_TESTER_STARTER_DURATION_LIMIT
              value: {{ .Values.starter.durationLimit | quote }}
            {{- end }}
            {{- if .Values.starter.processId }}
            - name: LOAD_TESTER_STARTER_PROCESS_ID
              value: {{ .Values.starter.processId | quote }}
            {{- end }}
            {{- if .Values.starter.bpmnXmlPath }}
            - name: LOAD_TESTER_STARTER_BPMN_XML_PATH
              value: {{ .Values.starter.bpmnXmlPath | quote }}
            {{- end }}
            {{- range $index, $value := .Values.starter.extraResources }}
            - name: LOAD_TESTER_STARTER_EXTRA_BPMN_MODELS_{{ $index }}_
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.starter.businessKey }}
            - name: LOAD_TESTER_STARTER_BUSINESS_KEY
              value: {{ .Values.starter.businessKey | quote }}
            {{- end }}
            {{- if .Values.starter.payloadPath }}
            - name: LOAD_TESTER_STARTER_PAYLOAD_PATH
              value: {{ .Values.starter.payloadPath | quote }}
            {{- end }}
            {{- if .Values.starter.logLevel }}
            - name: LOGGING_LEVEL_IO_CAMUNDA_ZEEBE
              value: {{ .Values.starter.logLevel | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: starter-config
                optional: true
          resources:
            {{- toYaml $.Values.starter.resources | nindent 12 }}
          ports:
            - containerPort: 9600
              name: "http"
{{- if .Values.global.extraConfig }}
          volumeMounts:
            - name: load-test-config
              mountPath: /usr/local/camunda/config/load-test-config.yaml
              subPath: load-test-config.yaml
      volumes:
        - name: load-test-config
          configMap:
            name: load-test-config
            defaultMode: 0754
{{- end }}
