{{- range $workerName, $worker := .Values.workers }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $workerName }}
  labels:
    app: {{ $workerName }}
spec:
  selector:
    matchLabels:
      app: {{ $workerName }}
  replicas: {{ $worker.replicas | default 3}}
  template:
    metadata:
      labels:
        app: {{ $workerName }}
        app.kubernetes.io/component: zeebe-client
      annotations:
        {{- include "camunda-load-tests.annotations" $ | nindent 8 }}
    spec:
      {{- if $.Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.image.pullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $workerName }}
          image: "{{ $.Values.global.image.repository }}/worker:{{ $.Values.global.image.tag }}"
          imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dconfig.override_with_env_vars=true
                {{- if $.Values.saas.enabled }}
                -Dapp.tls=true
                {{- else }}
                -Dapp.brokerUrl=http://{{ $.Values.global.connect.serviceName }}:26500
                -Dapp.brokerRestUrl=http://{{ $.Values.global.connect.serviceName }}:8080
                {{- end }}
                -Dapp.preferRest={{ $.Values.global.preferRest.enabled }}
                -Dzeebe.client.requestTimeout=62000
                {{- if $worker.capacity }}
                -Dapp.worker.capacity={{ $worker.capacity }}
                {{- end }}
                {{- if $worker.threads }}
                -Dapp.worker.threads={{ $worker.threads }}
                {{- end }}
                -Dapp.worker.pollingDelay=1ms
                {{- if $worker.completionDelay }}
                -Dapp.worker.completionDelay={{ $worker.completionDelay }}
                {{- else }}
                -Dapp.worker.completionDelay=50ms
                {{- end }}
                -Dapp.worker.workerName={{ $workerName | quote }}
                {{- if $worker.jobType }}
                -Dapp.worker.jobType={{ $worker.jobType | quote }}
                {{- end }}
                {{- if $worker.payloadPath }}
                -Dapp.worker.payloadPath={{ $worker.payloadPath | quote }}
                {{- end}}
                {{- if $worker.message }}
                -Dapp.worker.sendMessage=true
                -Dapp.worker.messageName={{ $worker.message.name | quote }}
                -Dapp.worker.correlationKeyVariableName={{ $worker.message.correlationVariable | quote }}
                {{- end }}
                -XX:+HeapDumpOnOutOfMemoryError
            {{- if $worker.logLevel }}
            - name: LOG_LEVEL
              value: {{ $worker.logLevel | quote }}
            {{- end }}
            {{- if $.Values.saas.enabled }}
            - name: ZEEBE_REST_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: zeebeRestAddress
            - name: ZEEBE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: clientId
            - name: ZEEBE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: clientSecret
            - name: ZEEBE_AUTHORIZATION_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: authServer
            - name: ZEEBE_TOKEN_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: authorizationAudience
            - name: ZEEBE_AUTH_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: authType
            - name: ZEEBE_GRPC_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ include "camunda-load-tests.credentials-name" $ }}
                  key: zeebeGrpcAddress
            {{- end }}
            {{- if $.Values.global.extraConfig }}
            # To be able to load a separate/additional configuration
            - name: SPRING_CONFIG_ADDITIONALLOCATION
              value: "/usr/local/camunda/config/load-test-config.yaml"
            {{- end }}
            {{- range $keyValue := $.Values.global.extraEnvVars }}
            - name: {{ $keyValue.name }}
              value: {{ $keyValue.value | quote }}
            {{- end }}
            ##
            ## Spring Boot compatible env vars (for migrated load tester, ignored by old HOCON app)
            ##
            - name: CAMUNDA_CLIENT_PREFER_REST_OVER_GRPC
              value: {{ $.Values.global.preferRest.enabled | quote }}
            {{- if not $.Values.saas.enabled }}
            - name: CAMUNDA_CLIENT_GRPC_ADDRESS
              value: "http://{{ $.Values.global.connect.serviceName }}:26500"
            - name: CAMUNDA_CLIENT_REST_ADDRESS
              value: "http://{{ $.Values.global.connect.serviceName }}:8080"
            {{- else }}
            - name: CAMUNDA_CLIENT_MODE
              value: "saas"
            - name: CAMUNDA_CLIENT_AUTH_METHOD
              value: "oidc"
            {{- end }}
            {{- if $worker.capacity }}
            - name: LOAD_TESTER_WORKER_CAPACITY
              value: {{ $worker.capacity | quote }}
            {{- end }}
            {{- if $worker.threads }}
            - name: LOAD_TESTER_WORKER_THREADS
              value: {{ $worker.threads | quote }}
            {{- end }}
            - name: LOAD_TESTER_WORKER_POLLING_DELAY
              value: "1ms"
            {{- if $worker.completionDelay }}
            - name: LOAD_TESTER_WORKER_COMPLETION_DELAY
              value: {{ $worker.completionDelay | quote }}
            {{- else }}
            - name: LOAD_TESTER_WORKER_COMPLETION_DELAY
              value: "50ms"
            {{- end }}
            - name: LOAD_TESTER_WORKER_WORKER_NAME
              value: {{ $workerName | quote }}
            {{- if $worker.jobType }}
            - name: LOAD_TESTER_WORKER_JOB_TYPE
              value: {{ $worker.jobType | quote }}
            {{- end }}
            {{- if $worker.payloadPath }}
            - name: LOAD_TESTER_WORKER_PAYLOAD_PATH
              value: {{ $worker.payloadPath | quote }}
            {{- end }}
            {{- if $worker.message }}
            - name: LOAD_TESTER_WORKER_SEND_MESSAGE
              value: "true"
            - name: LOAD_TESTER_WORKER_MESSAGE_NAME
              value: {{ $worker.message.name | quote }}
            - name: LOAD_TESTER_WORKER_CORRELATION_KEY_VARIABLE_NAME
              value: {{ $worker.message.correlationVariable | quote }}
            {{- end }}
            {{- if $worker.logLevel }}
            - name: LOGGING_LEVEL_IO_CAMUNDA_ZEEBE
              value: {{ $worker.logLevel | quote }}
            {{- end }}
          {{- if $worker.resources }}
          resources:
            {{- toYaml $worker.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9600
              name: "http"
{{- if $.Values.global.extraConfig }}
          volumeMounts:
            - name: load-test-config
              mountPath: /usr/local/camunda/config/load-test-config.yaml
              subPath: load-test-config.yaml
      volumes:
        - name: load-test-config
          configMap:
            name: load-test-config
            defaultMode: 0754
{{- end }}

---
{{- end }}
