apiVersion: v2
name: camunda-load-tests
description: A Helm chart for Camunda load tests
type: application
version: 0.1.1
appVersion: "8.8.0"
sources:
  - https://github.com/camunda/camunda-load-tests-helm
  - https://github.com/camunda/camunda
maintainers:
  - name: ChrisKujawa
    email: christopher.kujawa@camunda.com
annotations:
  artifacthub.io/links: |
    - name: Zeebe Repo
      url: https://github.com/camunda/camunda
    - name: Zeebe Docs
      url: https://docs.camunda.io/docs/components/zeebe/zeebe-overview/
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: "- kind: fixed\n  description: \"case sensitivity in CamundaExporter configuration\"\n"
